### PR TITLE
fix xarray remote tutorial data

### LINKED ISSUE #2: Notebook not compiling
The notebook is currently not compiling. The current build logs are [here](https://github.com/pangeo-data/pangeo-tutorial-gallery/runs/828454816?check_suite_focus=true), with an error of 

```
/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/binderbot/cli.py:14: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  f = asyncio.coroutine(f)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/binderbot/cli.py", line 95, in <module>
    sys.exit(main())  # pragma: no cover
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/binderbot/cli.py", line 17, in wrapper
    return loop.run_until_complete(f(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
```

This is different from the last time I tried to run this build, which yielded an error implying the notebook had tried to access an API too many times and exceeded the rate limit. Unsure why the errors are different. I will try to push minor changes to have different build logs to examine, which should help identify the problem.

### PR DESCRIPTION
**Pull request by scottyhq**
@salvis2 - hopefully this temporarily fixes #2. I've moved the tutorial data into a separate git repo (https://github.com/pangeo-data/tutorial-data), and the notebook just runs `git clone` to bring it into the local working directory

### CODE REVIEW

**Comment by salvis2** [comment]
Looks like the build encountered an error at 

```
ds_all = xr.open_mfdataset('/home/jovyan/.xarray_tutorial_data/sst/*nc', combine='by_coords')
```

with 

```
OSError: no files to open
```

**Comment by salvis2** [comment]
I'll try re-running the job.

**Comment by scottyhq** [comment]
The PR build is still using files in the master branch. This should also be added to the list of things to fix. See https://github.com/NCAR/cesm-lens-aws/pull/51#issuecomment-624151137. You'll just have to merge and see what happens

**Comment by salvis2** [comment]
Ah okay. I'll merge and make some PRs to this and the Landsat 8 tutorial so the binder config is on a different environment.

**Pull request merged**
